### ISSUE TITLE
ITC-3: Can't set an input to False with with M0006

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_implementations#45]
It is not possible to set an input to False with M0006

1. S0029 (forced input status) reports "00000..."
4. Setting input 2 with M0006 to status: True
3. S0003 (input status) reports "10000..."
4. Setting input 2 with M0006 to status: False
5. S0003 (input status) reports "10000..." (no change)

However, it is possible to force the input off using M0019

Tested with: ITC-3 v7.12.4 date 0-00-00 build 6278c141

**Comment by Rodgulgronademonen** [comment]
Seems to be fixed for ITC-3 ? It could be that we had the wrong settings in the configuration file earlier...

**Comment by otterdahl** [comment]
It seems the work after adding the following configuration option:
```json
"unforce-software-flag-default-state": "off"
```

**Comment by SwarcoPalm** [comment]
This is correct, and is due to the little bit missing handling of forcing of inputs.

If RSMP sets the input to 1, the TLC will keep the input as 1 indefinetly (there is no timeout specificed in the protocol). Same if it sets it to 0. But likely this input was already connected to a physical or otherwise input, how to allow the controller to go back to acting on the physical state of the input?

The way we accomplished this was by treating the command as a force-on command. So if you set it to 1, you force the input to 1 indefinetly. When you set it to 0, you allow other sources to override the input. By default that might not change the state of the input, so you observe it stays in 1. This is why we have the config option, telling it that it should return the input to 0 if it "unforced".

In the perfect world we should have had 3 states, force-on, force-off and un-force.

**Comment by otterdahl** [comment]
Thank you for clarifying this

**Comment by otterdahl** [comment]
Fixed (by setting configuration setting)
